project:
  type: website
  output-dir: docs
website:
  title: "Laura Díaz-Muñoz Manzanares"
  favicon: L.png
  navbar:
    right:
      - href: thesis.pdf
        text: PhD thesis
      - href: LauraCV.pdf
        text: CV
        
  page-footer: 
    background: light
    left: 
      - "Made in Quarto | Copyright 2023"
    right: 
      - icon: github
        href: https://github.com/lauradiazmm

format:
  html:
    link-external-newwindow: true
    theme: Solar
    css: styles.css
    mainfont: Nunito
    fontsize: 14pt


editor: visual